public class Association {
    public static void main(String args[]) {
        State tamilNadu = new State("Tamil Nadu", 130000, 38, 5000, 4000);
        State maharashtra = new State("Maharashtra", 307000, 36, 7000, 6000);
        State assam = new State("Assam", 78000, 33, 3000, 2000);

        State[] states = {tamilNadu, maharashtra, assam};

        India India_2023 = new India("India", 3287000, true, 10000, 2023);
        India India_2024 = new India("India", 3287000, true, 12000, 2024);
        India India_2025 = new India("India", 3287000, true, 20000, 2025);

        System.out.println("--- Revenues of India in 2022 ---");
        India_2023.calculateTotalRevenue(states);

        System.out.println("--- Revenues of India in 2023 ---");
        India_2023.calculateTotalRevenue(states);

        System.out.println(" --- Revenues of India in 2024 ---");
        India_2024.calculateTotalRevenue(states);

        System.out.println("--- Revenues of India in 2025 ---");
        India_2025.calculateTotalRevenue(states);
    }
}


class Country {
    String name;
    float area;
    boolean is_coastal;
    int year;

    Country(String n, float area, boolean is_coastal, int year) {
        this.name = n;
        this.area = area;
        this.is_coastal = is_coastal;
        this.year = year;
    }


    Revenue calculateGDP(State s[]) {
        int total = 0;
        for (State state : s) {
            total += state.calculateStateRevenue(year);
        }
        return new Revenue("GDP (Agri+Trade)", total);
    }
}

class State {
    String name;
    int area;
    int districts;
    int baseAgriRevenue;
    int baseTradeRevenue;

    State(String name, int area, int districts, int agriRevenue, int tradeRevenue) {
        this.name = name;
        this.area = area;
        this.districts = districts;
        this.baseAgriRevenue = agriRevenue;
        this.baseTradeRevenue = tradeRevenue;
    }


    int calculateStateRevenue(int year) {


        double agri = baseAgriRevenue + (year * 2);
        double trade = baseTradeRevenue * (year * 2);

        int r = (int)((agri + trade) * districts);
        System.out.println("The revenue generated by State " + name + " in " + year + " is: " + r);
        return r;
    }
}


class India extends Country {
    int gstRevenue;

    India(String n, float area, boolean is_coastal, int gst, int year) {
        super(n, area, is_coastal, year);
        this.gstRevenue = gst;
    }


    void calculateTotalRevenue(State s[]) {
        Revenue gdp = calculateGDP(s);
        Revenue gst = new Revenue("GST", gstRevenue);

        int total = gdp.amount + gst.amount;

        System.out.println(gdp);
        System.out.println(gst);
        System.out.println(">>> Total Revenue (GDP + GST) in " + year + " = " + total + "\n");
    }
}

class Revenue {
    String type;
    int amount;

    Revenue(String type, int amt) {
        this.type = type;
        this.amount = amt;
    }

    public String toString()
    {
        return type + " Revenue: " + amount;
    }
}
